apiVersion: v1
kind: Service
metadata:
  name: testing-app-k8s-service
spec:
  selector:
    app: testing-app-k8s
  ports:
    - protocol: TCP
      port: 7070
      targetPort: 7070
  type: LoadBalancer
